### ISSUE TITLE
建议 model id 改为 `moonshot-kimi`

### ISSUE THREAD

**Issue by arvinxx** [sherlcok314159/reverse-kimi#10]
万一后续官方推出了 `moonshot-v1` 的自动升级版本（类似gpt-3.5-turbo），那么现在这个 id 就冲突了。`moonshot-kimi` 大概率应该不会冲突，我想他们不至于直接把 kimi 作为模型服务提供出来吧。

**Comment by sherlcok314159** [comment]
感谢你的建议，不过应该是不会的，我看 api 的都是带后缀来标明最大长度

<img width="1045" alt="image" src="https://github.com/sherlcok314159/reverse-kimi/assets/76043326/df4a9df7-2400-4585-824d-83e415424b83">
