### ISSUE TITLE
手动部署，返回的内容有问题

### ISSUE THREAD

**Issue by HelloEveryonehh** [sherlcok314159/reverse-kimi#11]
采取手动部署的形式,其中config.json的内容如下
![image](https://github.com/sherlcok314159/reverse-kimi/assets/110333012/fbb65107-1703-422b-9579-f2e1358a9a97)
两个终端的无报错，并且显示请求正确
![image](https://github.com/sherlcok314159/reverse-kimi/assets/110333012/34702865-c5e5-43df-88c5-0d3eb2b3f463)
使用python请求，返回的内容如下
![image](https://github.com/sherlcok314159/reverse-kimi/assets/110333012/57a751b4-ff3b-469c-b921-4bb726bcceab)

**Comment by sherlcok314159** [comment]
预期情况，没有问题
