### ISSUE TITLE
接入到one-api后，新建渠道一直测试不通过

### ISSUE THREAD

**Issue by brucepeng** [sherlcok314159/reverse-kimi#13]
点击测试的时候会提示
错误:invalid character 'd' looking
for beginning of value

**Comment by sherlcok314159** [comment]
我使用正常，与本仓库无关， [参见这里是否对你有帮助](https://github.com/sherlcok314159/reverse-kimi/issues/3)

**Comment by sherlcok314159** [comment]
Close for no update.
