### ISSUE TITLE
有没有办法获得搜索的结果

### ISSUE THREAD

**Issue by smartliuhw** [sherlcok314159/reverse-kimi#14]
大佬，想请教一下，kimi在生成的时候会去网上搜索相应的网页来回复，有没有办法把它搜索到的内容（或者是网址）弄下来呢？目前试了下这个脚本是直接获得的生成结果

**Comment by sherlcok314159** [comment]
已在最新的修改中加入功能，你需要拉取最新的镜像：

<img width="1612" alt="图片" src="https://github.com/sherlcok314159/reverse-kimi/assets/76043326/c32a2da6-0b12-4c7c-98e6-56cdbaf8a124">
