### ISSUE TITLE
部署之后如何请求？

### ISSUE THREAD

**Issue by Payne-Wang** [sherlcok314159/reverse-kimi#3]
大佬好，已经根据说明用docker部署好了，请问如何请求呢？
openai请求时需要传sk-XXX和模型名称，这个该怎么传这些呢？谢谢！

**Comment by sherlcok314159** [comment]
你可以重新拉取最新的镜像，然后你可以参见 README 中的注意事项这一节，然后登入文档（/docs）查看示例，里面提供了命令行调用的方法

如果你是使用第三方 UI，比如 Chat-Next-Web 或 lobe-chat，可以填写以下参数：

```
api_endpoint: 'http://localhost:6867/v1/chat/completitions' （这里是为了列全，正常到 /v1 即可，后面不用补全）
token: 'Bearer ...' （也就是你在 config.json 中设置的密钥）
messages: 这个由 UI 自动搞定，你不用操心
```

**Comment by Payne-Wang** [comment]
感谢大佬指导，但是我部署后报401，不知道啥原因，如下:
![image](https://github.com/sherlcok314159/reverse-kimi/assets/44337721/f6758c4b-6ace-47bb-be84-3f813a942bad)

我的configjson如下：
![image](https://github.com/sherlcok314159/reverse-kimi/assets/44337721/fd7ab184-509a-4a5f-9719-909d7bff5474)

我是使用oneapi请求的，api地址写的是http://我的IP:6867  密钥写的是config.json中的token值，模型写的是kimi

请指教，谢谢

**Comment by sherlcok314159** [comment]
401 是因为你鉴权错误，如果用 One-Api，你应该填的是 Bearer Ab...，你要不仔细看看有没有填错

**Comment by Payne-Wang** [comment]
> 401 是因为你鉴权错误，如果用 One-Api，你应该填的是 Bearer Ab...，你要不仔细看看有没有填错

大佬，我按照Bearer AbXXXX这种填写了，仍然报401。模型我写的kimi，正常应该写什么？我在readme中没有找到

**Comment by sherlcok314159** [comment]
那就奇怪了，我也这么用的，估计可能是你拼写或是不起眼的小问题

<img width="1410" alt="图片" src="https://github.com/sherlcok314159/reverse-kimi/assets/76043326/6750e3ca-89ea-4124-9d10-863e1804b3c6">

我刚刚重新构建了新的镜像，你用最新的镜像试试看，我加了 debug 输出逻辑

**Comment by Payne-Wang** [comment]
> 那就奇怪了，我也这么用的，估计可能是你拼写或是不起眼的小问题
> 
> <img alt="图片" width="1410" src="https://private-user-images.githubusercontent.com/76043326/311616013-6750e3ca-89ea-4124-9d10-863e1804b3c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDY5NzcsIm5iZiI6MTcxMDE0NjY3NywicGF0aCI6Ii83NjA0MzMyNi8zMTE2MTYwMTMtNjc1MGUzY2EtODllYS00MTI0LTlkMTAtODYzZTE4MDRiM2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA4NDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNzZlMDI1YzE2N2Q5MDZjNTI2OTA4YzY5OTE3MmU3NWNmZDQwYTVhYWM1NzlhZGFhMzc2YWQwZGYyOTZiYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b7qJ9-xDAbf7EKxA7snke4F7obMGF6vj8XIK3_LiNE8">
> 我刚刚重新构建了新的镜像，你用最新的镜像试试看，我加了 debug 输出逻辑

可以了，我更新了镜像，然后将模型名称改为moonshot-v1，就正常了，谢谢大佬
