### ISSUE TITLE
使用了chatgpt-web这个项目后，对话无法自动结束

### ISSUE THREAD

**Issue by dqzboy** [sherlcok314159/reverse-kimi#5]
大佬，在使用chatgpt-web这个项目的时候（前端项目地址：https://github.com/chatgpt-web-dev/chatgpt-web）
无法自动结束；使用coze-discord-proxy这个代理项目可以正常结束对话
![image](https://github.com/sherlcok314159/reverse-kimi/assets/42825450/c9e34e00-bf53-46b0-ba99-c5a4a6afeccd)
![image](https://github.com/sherlcok314159/reverse-kimi/assets/42825450/51a86caa-ea2c-4f5f-80b9-248bb5c23713)

**Comment by sherlcok314159** [comment]
如果排除网络原因，加上重试仍为这种情况，我想应该不是本项目的原因，流失输出默认会有个 end（标准的 openai 流失输出），很有可能是你的 webui 对此实现有问题，该现象我并未在 lobe-chat 抑或是 chat-next-web 上复现

**Comment by dqzboy** [comment]
> 如果排除网络原因，加上重试仍为这种情况，我想应该不是本项目的原因，流式输出默认会有个 end（标准的 openai 流式输出），很有可能是你的 webui 对此实现有问题，该现象我并未在 lobe-chat 抑或是 chat-next-web 上复现

网络应该是没问题的，测试chatgpt-on-wechat也不行，模型指定为moonshot-v1也不行
![image](https://github.com/sherlcok314159/reverse-kimi/assets/42825450/68607d27-8059-4a47-a8f2-3dbcda430242)

**Comment by sherlcok314159** [comment]
这显然是这些 UI 并不支持标准流式输出，你应该找这些项目，或者换更加标准的 UI 实现，比如我提到的两款
