### ISSUE TITLE
API调用怎么流式输出

### ISSUE THREAD

**Issue by ZhaoShuang1995** [sherlcok314159/reverse-kimi#7]
按照常规的llm调用方式进行api request，但是返回的结果无法呈流式输出，示例代码如下：

    url = "http://xxxxxx/v1/chat/completions"
    payload = {
        "model": "moonshot-v1",
        "temperature": 0,
        "messages": [{"role": "user", "content": prompt}],
        "stream": True
    }
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer xxxxxxxx"
    }
    response = requests.request("POST", url, headers=headers, json=payload, stream=True)
    for chunk in response.iter_lines(chunk_size=1024):
        xxxxxx

这个方式在调用chatgpt或vllm部署的模型时都是OK的，但是这个项目的服务中无法流式输出

**Comment by sherlcok314159** [comment]
我之前关于鉴权的文档写的不对，重新修改了文档，可以查看下，假如你在 config.json 中设置 token 为 12345678，在 Python 调用时用 Bearer 12345678

关于详细代码，可以使用下列：

```python
url = "http://127.0.0.1:6867/v1/chat/completions"
prompt = [{'content': '天空为什么不是红色', 'role': 'user'}]

payload = {
    "model": "moonshot-v1",
    "messages": [{"role": "user", "content": prompt}],
}
headers = {
    "Authorization": "Bearer 12345678"
}
response = requests.request("POST", url, headers=headers, json=payload)

for chunk in response.iter_lines(chunk_size=1024):
    print(chunk)
```

<img width="1117" alt="图片" src="https://github.com/sherlcok314159/reverse-kimi/assets/76043326/84a558f5-3e4c-4cea-aebb-6d7c3d0704e5">

**Comment by Ivesfsy** [comment]
docker部署成功后可以通过newapi使用，但是宝塔反向代理项目后设置nginx：proxy_buffering off;后依旧不能流式输出，有好的办法吗？

**Comment by sherlcok314159** [comment]
这种是你自己 UI 或其他的问题，我无论用 lobe-chat 还是 chatgpt-next-web 抑或是 python 本地输出都可以做到流式

**Comment by ZhaoShuang1995** [comment]
> 我之前关于鉴权的文档写的不对，重新修改了文档，可以查看下，假如你在 config.json 中设置 token 为 12345678，在 Python 调用时用 Bearer 12345678
> 
> 关于详细代码，可以使用下列：
> 
> ```python
> url = "http://127.0.0.1:6867/v1/chat/completions"
> prompt = [{'content': '天空为什么不是红色', 'role': 'user'}]
> 
> payload = {
>     "model": "moonshot-v1",
>     "messages": [{"role": "user", "content": prompt}],
> }
> headers = {
>     "Authorization": "Bearer 12345678"
> }
> response = requests.request("POST", url, headers=headers, json=payload)
> 
> for chunk in response.iter_lines(chunk_size=1024):
>     print(chunk)
> ```
> 
> <img alt="图片" width="1117" src="https://private-user-images.githubusercontent.com/76043326/314359810-84a558f5-3e4c-4cea-aebb-6d7c3d0704e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODU0ODMsIm5iZiI6MTcxMDk4NTE4MywicGF0aCI6Ii83NjA0MzMyNi8zMTQzNTk4MTAtODRhNTU4ZjUtM2U0Yy00Y2VhLWFlYmItNmQ3YzNkMDcwNGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAxMzk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZTlhN2MzMTliZTU3ZTY3YzA4NzIzOGNhMjFjMmIzZWU5ZDRkNGQ3ODM5OGZjNDM0N2E2MWE4NWU1MWVkMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.foD-85Kf53_MbgpaUsBeVkxWz5pa8vDBCO1KWXvJnCs">

麻烦再问一下，您这个例子中的流式输出，是那种打字机式的每隔很短的时间输出一个chunk？还是等待了一点时间后一次性输出了这样的一长段流式内容？我这边自己测试的一直都是后一种...

**Comment by sherlcok314159** [comment]
这个显然是后一种，等待的时间是跟 Kimi 进行交互，交互完之后文本肯定是很快输出的，既然流式输出没问题，issues 就关了

**Comment by ZhaoShuang1995** [comment]
> 这个显然是后一种，等待的时间是跟 Kimi 进行交互，交互完之后文本肯定是很快输出的，既然流式输出没问题，issues 就关了

好的，那感觉这个其实不算是流式输出了... 等待的时间其实就是完整的大模型给出答案的时间了，如果回答内容变长等待的时间也会更长，且每个chunk之间的输出时间几乎为0

**Comment by sherlcok314159** [comment]
这个没办法，因为是逆向的，你得等交互完，你要想完全流式建议去用 api

**Comment by ZhaoShuang1995** [comment]
> 这个没办法，因为是逆向的，你得等交互完，你要想完全流式建议去用 api

明白，多谢！
