### ISSUE TITLE
已经 PR 功能到 LobeChat 并讨论几个使用问题

### ISSUE THREAD

**Issue by MapleEve** [sherlcok314159/reverse-kimi#8]
https://github.com/lobehub/lobe-chat/pull/1659

1. 他会一段时间刷新网页的 access token，但是这样导致反应比较慢，只能用来chat
2. 关于文件识别、图片识别，只能识别很简单的一点 base64 图片，太大的读不出来，文件也有可能读不出
3. 网络搜索：读取比较新的新闻，比如刚发生的财经新闻只能给当天的新闻，对网页的读取有防爬取机制的好像不是很兼容，比如财联社的新闻

**Comment by sherlcok314159** [comment]
我不大理解你的意思，本来我的示例就包含文件识别，图片识别，以及网络搜索

**Comment by MapleEve** [comment]
> 我不大理解你的意思，本来我的示例就包含文件识别，图片识别，以及网络搜索

看了你发的示例，但是在用Kimi的时候，我发现他实际上不会读网页，不像GPTs那样真正的用browser打开了一个网页

**Comment by sherlcok314159** [comment]
Nope

Kimi 本身是可以读网页，你指的是那种 function calling 功能

**Comment by sherlcok314159** [comment]
你有兴趣可以搞或者 PR 上来，I am open to it. 不过这背离我做这个的初衷，加上时间有限，我并不会花时间搞这个

**Comment by sherlcok314159** [comment]
参见 #9，这个是 BUG，我已经修复，用最新的试试看

**Comment by MapleEve** [comment]
> 你有兴趣可以搞或者 PR 上来，I am open to it. 不过这背离我做这个的初衷，加上时间有限，我并不会花时间搞这个

我也想啊，Python实在是搞不定，你看我profile的wakatime面板就知道stack了
