### ISSUE TITLE
docker部署成功，但是联网阅读、文件阅读功能似乎不行

### ISSUE THREAD

**Issue by DigitalNomad-Chat** [sherlcok314159/reverse-kimi#9]
项目在docker部署成功，可以进行对话。但是发送网址给它，它无法阅读网址内部内容。发送文件链接也无法阅读文件内容。

**Comment by sherlcok314159** [comment]
给的链接是什么？是国内的吗？国外的不行

**Comment by myhyday** [comment]
> 链接能贴出来吗

就是凤凰网的新闻，随便挑一个都行

我觉得和网址没有关系。我看您的演示截图，您那边是可以读取链接，让它搜索网页它也会给出参考资料链接。我这边都没有，不知道是因为部署环境的原因，还是其他什么原因。

我看上一个issue的用户，跟我反馈的内容似乎是差不多的。

**Comment by sherlcok314159** [comment]
的确问题存在，我已修复该问题，请使用最新版 docker 尝试

<img width="900" alt="image" src="https://github.com/sherlcok314159/reverse-kimi/assets/76043326/9c8c24a0-3773-4f26-8ebc-bc69d634c7ab">

<img width="1582" alt="image" src="https://github.com/sherlcok314159/reverse-kimi/assets/76043326/dfa4bd6d-f38e-4b60-95a2-ae803349e97f">

**Comment by sherlcok314159** [comment]
另外，Kimi 自带关键词过滤，尤其是政治类新闻较容易触发，很可能没有返回或错误返回，使用时注意

**Comment by myhyday** [comment]
> 的确问题存在，我已修复该问题，请使用最新版 docker 尝试
> 
> <img alt="image" width="900" src="https://private-user-images.githubusercontent.com/76043326/315307091-9c8c24a0-3773-4f26-8ebc-bc69d634c7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzA4NTAsIm5iZiI6MTcxMTAzMDU1MCwicGF0aCI6Ii83NjA0MzMyNi8zMTUzMDcwOTEtOWM4YzI0YTAtMzc3My00ZjI2LThlYmMtYmM2OWQ2MzRjN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0MTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZWYyYTZjMTk0OTIzZTM0YTEzZDBiNjI5NmYyNzMzMmI1ZWUwYmRhOWFmZTE4ZGZkNGZiMjFhZDU0NjAxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._gYeIg8HFEHHp9K-hij0kbfFTP6gB-TEiVd-WvCV9Ls"> <img alt="image" width="1582" src="https://private-user-images.githubusercontent.com/76043326/315306993-dfa4bd6d-f38e-4b60-95a2-ae803349e97f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzA4NTAsIm5iZiI6MTcxMTAzMDU1MCwicGF0aCI6Ii83NjA0MzMyNi8zMTUzMDY5OTMtZGZhNGJkNmQtZjM4ZS00YjYwLTk1YTItYWU4MDMzNDllOTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0MTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTkxZjc0Y2Y5YjZkODJkMWUzYmIxNWIzZTFlZjVhYWIwNGRiNTM5YzIxNmVlNzA5ZGE3MTI5ZTZiZmI2OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KAhgWrepOXvtc9tdbz1cWLL6DRA8Mlto5n4jBshxIzU">

测试，可以了，感谢，辛苦大神了
